### ISSUE TITLE
Bug, not "bachi"

### ISSUE THREAD

**Issue by pingumen96** [requests/requests-docs-it#1]
Also Italian programmers use the term 'bug' to identify an error, but that's not all, 'bachi' word is not used at all.

**Comment by csparpa** [comment]
I've heard Italian coworkers using the word "baco/bachi" to identify software bugs in all of my previous jobs - and I've been using it myself as well... What's wrong with it?

**Comment by pingumen96** [comment]
Anch'io sono italiano e invece ho sempre sentito dire 'bug'... Niente,
allora credo vada bene così, 'bachi' mi suonava strano ma se si usa è
corretto.
Il 15/lug/2015 09:34, "Claudio Sparpaglione" notifications@github.com ha
scritto:
